























































































































};  }    }      MIN_MARKET_CAP: 5000000000 // $5B minimum market cap      MIN_VOLUME_24H: 100000000, // $100M minimum daily volume      ],        'BNBUSDT'              // Then BNB        'ETHUSDT',              // Then ETH        'BTCUSDT',              // Train on BTC first      TRAINING_ORDER: [      INITIAL_PAIR: 'BTCUSDT',  // Start with BTC    PAIRS_STRATEGY: {    ],      'trend_strength'      'atr',      'bb_lower',      'bb_upper',      'macd',      'rsi',      'volume',      'close',    FEATURES: [    EPOCHS: 100,    BATCH_SIZE: 32,    VALIDATION_SPLIT: 0.2,    MIN_TRAINING_SAMPLES: 1000,    LOOKBACK_DAYS: 180,        // 6 months historical data  TRAINING: {  },    ]      }        priority: 4        description: 'Avalanche/USDT',        maxLeverage: 5,        minOrderSize: 10,        symbol: 'AVAXUSDT',      {      },        priority: 4        description: 'Solana/USDT',        maxLeverage: 5,        minOrderSize: 10,        symbol: 'SOLUSDT',      {    EXPERIMENTAL: [    ],      }        priority: 3        description: 'Binance Coin/USDT',        maxLeverage: 8,        minOrderSize: 10,        symbol: 'BNBUSDT',      {      },        priority: 2        description: 'Ethereum/USDT',        maxLeverage: 10,        minOrderSize: 10,        symbol: 'ETHUSDT',      {    SECONDARY: [    },      priority: 1      description: 'Bitcoin/USDT',      maxLeverage: 10,      minOrderSize: 10,      // Minimum order in USDT      symbol: 'BTCUSDT',    PRIMARY: {  TRADING_PAIRS: {  },    }      MAX_HOLDING_TIME: 48     // Max 48 hours per position      TRAILING_STOP: 0.015,    // 1.5% trailing stop    EXIT_CONDITIONS: {    },      TREND_CONFIRMATION: true // Require trend confirmation      MIN_VOLUME: 1000000,     // Minimum 24h volume      MIN_CONFIDENCE: 0.7,     // 70% minimum model confidence    ENTRY_CONDITIONS: {    },      }        STD: 2        PERIOD: 20,      BB: {      },        SIGNAL: 9        SLOW: 26,        FAST: 12,      MACD: {      },        OVERSOLD: 30        OVERBOUGHT: 70,        PERIOD: 14,      RSI: {    INDICATORS: {    SYMBOLS: ['BTCUSDT'],      // Start with BTC    TIMEFRAMES: ['1h', '4h'],  // Multiple timeframe analysis  STRATEGY: {  },    TAKE_PROFIT: 0.04         // 4% take profit    STOP_LOSS: 0.02,          // 2% stop loss    },      MIN: 2                  // Minimum leverage      MAX: 10,                // Maximum leverage      DEFAULT: 5,              // Default leverage    LEVERAGE: {    MAX_DRAWDOWN: 0.15,        // 15% max drawdown    MAX_DAILY_RISK: 0.06,      // 6% max daily risk    MAX_RISK_PER_TRADE: 0.02,  // 2% risk per trade  RISK_MANAGEMENT: {  },    MAX_POSITION_SIZE: 100     // Maximum trade size $100    MIN_POSITION_SIZE: 10,     // Minimum trade size $10    INITIAL_BALANCE: 500,      // Starting with $500  CAPITAL: {export const TRADING_CONFIG = {